name: nakama-node1
data_dir: "./data/"

logger:
  level: "DEBUG"
  stdout: true
  file: ""

console:
  port: 7351
  username: "admin"
  password: "password"  # Change in production!
  
socket:
  server_key: "defaultkey"  # Change in production!
  port: 7350
  max_message_size_bytes: 4096
  outgoing_queue_size: 128
  ping_period_ms: 15000
  pong_wait_ms: 25000
  write_wait_ms: 10000

runtime:
  # Load TypeScript modules from modules/ directory
  path: "/nakama/data/modules"
  http_key: "defaulthttpkey"  # Change in production!
  
database:
  address:
    - "postgres:localdb@postgres:5432/nakama"
  conn_max_lifetime_ms: 60000
  max_open_conns: 100
  max_idle_conns: 10

session:
  token_expiry_sec: 7200
  refresh_token_expiry_sec: 3600
